/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author madhuka
 */
public class calculator extends javax.swing.JFrame {
    
    double answer;
    
    int sphereClick;
    int tetraClick;
    int cubeClick;
    int cylinderClick;
    int pyramidClick;

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        radioSphere = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        circleRadiusText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioTriangle = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tetraSideText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radioCube = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cubeBaseText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        radioCylinder = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        cylinderHeightText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cylinderRadiusText = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnVolume = new javax.swing.JButton();
        btnArea = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        radioPyramid = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        pyramidBaseText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pyramidFaceHeightText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pyramidFaceWidthText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(34, 24, 14));
        setForeground(java.awt.Color.black);

        display.setEditable(false);
        display.setBackground(new java.awt.Color(51, 47, 42));
        display.setColumns(20);
        display.setForeground(java.awt.Color.white);
        display.setRows(5);
        display.setAutoscrolls(false);
        jScrollPane1.setViewportView(display);

        jPanel7.setBackground(new java.awt.Color(36, 23, 9));

        jPanel1.setBackground(new java.awt.Color(135, 229, 150));

        radioSphere.setBackground(new java.awt.Color(135, 229, 150));
        buttonGroup1.add(radioSphere);
        radioSphere.setText("Sphere");
        radioSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSphereActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Radius:");

        circleRadiusText.setText("type here");
        circleRadiusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleRadiusTextActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(239, 24, 24));
        jLabel12.setText("*can enter in any unit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(radioSphere, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(circleRadiusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSphere)
                    .addComponent(jLabel1)
                    .addComponent(circleRadiusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(236, 196, 102));

        radioTriangle.setBackground(new java.awt.Color(236, 196, 102));
        buttonGroup1.add(radioTriangle);
        radioTriangle.setText("Tetrahedron");
        radioTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTriangleActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Side:");

        tetraSideText.setText("type here");
        tetraSideText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tetraSideTextActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(239, 24, 24));
        jLabel14.setText("*for regular tetrahedron only!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(radioTriangle)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(tetraSideText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTriangle)
                    .addComponent(jLabel2)
                    .addComponent(tetraSideText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(117, 179, 236));

        radioCube.setBackground(new java.awt.Color(117, 179, 236));
        buttonGroup1.add(radioCube);
        radioCube.setText("Cube");
        radioCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCubeActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter Base:");

        cubeBaseText.setText("type here");
        cubeBaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeBaseTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(radioCube, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(cubeBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCube)
                    .addComponent(jLabel7)
                    .addComponent(cubeBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(206, 180, 242));

        radioCylinder.setBackground(new java.awt.Color(206, 180, 242));
        buttonGroup1.add(radioCylinder);
        radioCylinder.setText("Cylinder");
        radioCylinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCylinderActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Height");

        cylinderHeightText.setText("type here");

        jLabel9.setText("Enter radius:");

        cylinderRadiusText.setText("type here");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(radioCylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(cylinderHeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(70, 70, 70)
                .addComponent(cylinderRadiusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCylinder)
                    .addComponent(jLabel8)
                    .addComponent(cylinderHeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cylinderRadiusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(50, 31, 12));

        btnVolume.setForeground(new java.awt.Color(80, 40, 40));
        btnVolume.setText("Calculate Volume");
        btnVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumeActionPerformed(evt);
            }
        });

        btnArea.setText("Calculate Area");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(234, 174, 205));

        radioPyramid.setBackground(new java.awt.Color(234, 174, 205));
        buttonGroup1.add(radioPyramid);
        radioPyramid.setText("Pyramid");
        radioPyramid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPyramidActionPerformed(evt);
            }
        });

        jLabel10.setText("Enter Base Length:");

        pyramidBaseText.setText("type here");

        jLabel13.setText("Pyramid height:");

        pyramidFaceHeightText.setText("type here");
        pyramidFaceHeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyramidFaceHeightTextActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(239, 24, 24));
        jLabel15.setText("*for right rectangular pyramid only!");

        jLabel16.setText("Enter Base Width:");

        pyramidFaceWidthText.setText("type here");
        pyramidFaceWidthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyramidFaceWidthTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radioPyramid, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(37, 37, 37)
                        .addComponent(pyramidBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pyramidFaceHeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(37, 37, 37)
                            .addComponent(pyramidFaceWidthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPyramid)
                    .addComponent(jLabel10)
                    .addComponent(pyramidBaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pyramidFaceWidthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pyramidFaceHeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void circleRadiusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleRadiusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circleRadiusTextActionPerformed

    private void radioTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTriangleActionPerformed
        // TODO add your handling code here:
        tetraClick=1;
    }//GEN-LAST:event_radioTriangleActionPerformed

    private void tetraSideTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tetraSideTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tetraSideTextActionPerformed

    private void radioCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCubeActionPerformed
        // TODO add your handling code here:
        cubeClick = 1;
    }//GEN-LAST:event_radioCubeActionPerformed

    private void cubeBaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeBaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cubeBaseTextActionPerformed

    private void pyramidFaceHeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyramidFaceHeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pyramidFaceHeightTextActionPerformed

    private void radioSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSphereActionPerformed
        // TODO add your handling code here:
        sphereClick=1;
    }//GEN-LAST:event_radioSphereActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        // TODO add your handling code here:
        if (sphereClick > 0) {
            double r = Double.parseDouble(String.valueOf(circleRadiusText.getText()));
            answer = 4* 3.14159 * r * r;
            display.setText(String.valueOf(answer));
        }
        
        if (tetraClick > 0) {
            double r = Double.parseDouble(String.valueOf(tetraSideText.getText()));
            double root = Math.sqrt(3);
            answer = r*r*root;
            display.setText(String.valueOf(answer));
        }
        
        if (cubeClick > 0) {
            double s = Double.parseDouble(String.valueOf(cubeBaseText.getText()));
            answer = 4*6*s;
            display.setText(String.valueOf(answer));
        }
        
        if (cylinderClick > 0) {
            double h = Double.parseDouble(String.valueOf(cylinderHeightText.getText()));
            double r = Double.parseDouble(String.valueOf(cylinderRadiusText.getText()));
            answer = (h*2*r*3.14159)+(3.14159 * r * r * 2);
            display.setText(String.valueOf(answer));
        }    
          
        if (pyramidClick > 0) {
            double l = Double.parseDouble(String.valueOf(pyramidBaseText.getText()));
            double h = Double.parseDouble(String.valueOf(pyramidFaceHeightText.getText()));
            double w = Double.parseDouble(String.valueOf(pyramidFaceWidthText.getText()));
            double x = l*w;
            double y = l*(Math.sqrt(((w/2)*(w/2))+(h*h)));
            double z = w*(Math.sqrt(((l/2)*(l/2))+(h*h)));
            answer = x+y+z;
            display.setText(String.valueOf(answer));
        }         
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumeActionPerformed
        // TODO add your handling code here:
        if (sphereClick > 0) {
            double r = Double.parseDouble(String.valueOf(circleRadiusText.getText()));
            answer = (4/3)* 3.14159 * r * r;
            display.setText(String.valueOf(answer));
        }
        
        if (tetraClick > 0) {
            double r = Double.parseDouble(String.valueOf(tetraSideText.getText()));
            double root = Math.sqrt(2);
            answer = (r*r*r)/(6*root);
            display.setText(String.valueOf(answer));
        }
        
        if (cubeClick > 0) {
            double s = Double.parseDouble(String.valueOf(cubeBaseText.getText()));
            answer = 4*s*s;
            display.setText(String.valueOf(answer));
        }
        
        if (cylinderClick > 0) {
            double h = Double.parseDouble(String.valueOf(cylinderHeightText.getText()));
            double r = Double.parseDouble(String.valueOf(cylinderRadiusText.getText()));
            answer = h*(3.14159 * r * r);
            display.setText(String.valueOf(answer));
        }
        
        if (pyramidClick > 0) {
            double b = Double.parseDouble(String.valueOf(pyramidBaseText.getText()));
            double h = Double.parseDouble(String.valueOf(pyramidFaceHeightText.getText()));
            double w = Double.parseDouble(String.valueOf(pyramidFaceWidthText.getText()));
            answer = (b*h*w)/3;
            display.setText(String.valueOf(answer));
        }
    }//GEN-LAST:event_btnVolumeActionPerformed

    private void radioCylinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCylinderActionPerformed
        // TODO add your handling code here:
        cylinderClick=1;
    }//GEN-LAST:event_radioCylinderActionPerformed

    private void radioPyramidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPyramidActionPerformed
        // TODO add your handling code here:
        pyramidClick=1;
    }//GEN-LAST:event_radioPyramidActionPerformed

    private void pyramidFaceWidthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyramidFaceWidthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pyramidFaceWidthTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnVolume;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField circleRadiusText;
    private javax.swing.JTextField cubeBaseText;
    private javax.swing.JTextField cylinderHeightText;
    private javax.swing.JTextField cylinderRadiusText;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pyramidBaseText;
    private javax.swing.JTextField pyramidFaceHeightText;
    private javax.swing.JTextField pyramidFaceWidthText;
    private javax.swing.JRadioButton radioCube;
    private javax.swing.JRadioButton radioCylinder;
    private javax.swing.JRadioButton radioPyramid;
    private javax.swing.JRadioButton radioSphere;
    private javax.swing.JRadioButton radioTriangle;
    private javax.swing.JTextField tetraSideText;
    // End of variables declaration//GEN-END:variables
}
