/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycalculator;

/**
 *
 * @author Madhuka De Silva
 */
public class Calculator extends javax.swing.JFrame {

    double firstNum;
    double secondNum;
    double total;
    double plusMinus;
    
    int plusClick;
    int minusClick;
    int multiplyClick;
    int divideClick;
    int decimalClick;
    int squareClick;
    int otherClick;
    int cubeClick;
    int reciprocClick;
    int powClick;
    int powMoreClick;
    int modulusClick;
    
    
    
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        myCalculator1 = new mycalculator.MyCalculator();
        display = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        integerValue = new javax.swing.JButton();
        btnSinh = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        pow = new javax.swing.JButton();
        btnRootMore = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnCube = new javax.swing.JButton();
        btnCubeRoot = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        btnModulus = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnPowerTen = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        btnRoot = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnReciproc = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 228, 241));

        display.setFocusable(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Degrees");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Radians");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Grads");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        jPanel1.add(jRadioButton3);

        jButton1.setText("Null");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jButton2.setText("Inv");
        jPanel6.add(jButton2);

        jButton3.setText("In");
        jPanel6.add(jButton3);

        jButton4.setText("(");
        jPanel6.add(jButton4);

        jButton5.setText(")");
        jPanel6.add(jButton5);

        integerValue.setText("int");
        integerValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integerValueActionPerformed(evt);
            }
        });
        jPanel6.add(integerValue);

        btnSinh.setText("sinh");
        btnSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhActionPerformed(evt);
            }
        });
        jPanel6.add(btnSinh);

        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });
        jPanel6.add(btnSin);

        btnSquare.setText("x2");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });
        jPanel6.add(btnSquare);

        jButton10.setText("n!");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);

        jButton11.setText("dms");
        jPanel6.add(jButton11);

        jButton12.setText("cosh");
        jPanel6.add(jButton12);

        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });
        jPanel6.add(btnCos);

        pow.setText("x^y");
        pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powActionPerformed(evt);
            }
        });
        jPanel6.add(pow);

        btnRootMore.setText("y√x");
        btnRootMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootMoreActionPerformed(evt);
            }
        });
        jPanel6.add(btnRootMore);

        jButton16.setText("fi");
        jPanel6.add(jButton16);

        jButton17.setText("tanh");
        jPanel6.add(jButton17);

        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        jPanel6.add(btnTan);

        btnCube.setText("x3");
        btnCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubeActionPerformed(evt);
            }
        });
        jPanel6.add(btnCube);

        btnCubeRoot.setText("3√x");
        btnCubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubeRootActionPerformed(evt);
            }
        });
        jPanel6.add(btnCubeRoot);

        jButton21.setText("F-E");
        jPanel6.add(jButton21);

        jButton22.setText("Exp");
        jPanel6.add(jButton22);

        btnModulus.setText("Mod");
        btnModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulusActionPerformed(evt);
            }
        });
        jPanel6.add(btnModulus);

        btnLog.setText("log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel6.add(btnLog);

        btnPowerTen.setText("10x");
        btnPowerTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerTenActionPerformed(evt);
            }
        });
        jPanel6.add(btnPowerTen);

        jButton26.setText("MC");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton26);

        jButton27.setText("MR");
        jPanel7.add(jButton27);

        jButton28.setText("MS");
        jPanel7.add(jButton28);

        jButton29.setText("M+");
        jPanel7.add(jButton29);

        jButton30.setText("M-");
        jPanel7.add(jButton30);

        jButton31.setText("left");
        jPanel7.add(jButton31);

        jButton32.setText("CE");
        jPanel7.add(jButton32);

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel7.add(btnC);

        jButton34.setText("+-");
        jPanel7.add(jButton34);

        btnRoot.setText("√");
        btnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootActionPerformed(evt);
            }
        });
        jPanel7.add(btnRoot);

        btn7.setText(" 7 ");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel7.add(btn7);

        btn8.setText(" 8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel7.add(btn8);

        btn9.setText(" 9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel7.add(btn9);

        btnDivide.setText(" /");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        jPanel7.add(btnDivide);

        jButton40.setText(" %");
        jPanel7.add(jButton40);

        btn4.setText(" 4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel7.add(btn4);

        btn5.setText(" 5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel7.add(btn5);

        btn6.setText(" 6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel7.add(btn6);

        btnMultiply.setText(" *");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        jPanel7.add(btnMultiply);

        btnReciproc.setText("1/x");
        btnReciproc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciprocActionPerformed(evt);
            }
        });
        jPanel7.add(btnReciproc);

        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(55, 23));
        btn1.setMinimumSize(new java.awt.Dimension(55, 23));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel7.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel7.add(btn2);

        btn3.setText(" 3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel7.add(btn3);

        btnMinus.setText(" -");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        jPanel7.add(btnMinus);

        btnEqual.setText(" =");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        jPanel7.add(btnEqual);

        btn0.setText(" 0 ");
        btn0.setMaximumSize(new java.awt.Dimension(55, 23));
        btn0.setMinimumSize(new java.awt.Dimension(55, 23));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel7.add(btn0);

        btnDecimal.setText(" . ");
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });
        jPanel7.add(btnDecimal);

        btnPlus.setText(" + ");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        jPanel7.add(btnPlus);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("View");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Copy  Ctrl+C");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Paste Ctrl+V");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem3.setText("View help F1");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("About Calculator");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void btnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        double sqrt=Math.sqrt(firstNum);
        display.setText(String.valueOf(sqrt));
        // display.setText(""+sqrt);
        
    }//GEN-LAST:event_btnRootActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+btn1.getText());
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+btn2.getText());
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText()+".");
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        plusClick=1;
        decimalClick=0;
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        display.setText("");
        decimalClick=0;
    }//GEN-LAST:event_btnCActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        if (otherClick>0){
            if(squareClick>0){
            total=firstNum * firstNum ;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            squareClick=0;
            otherClick=0;
        }
            else if(cubeClick>0){
            total=firstNum * firstNum * firstNum;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            cubeClick=0;
            otherClick=0;
        }
            else if(reciprocClick>0){
            total=1/firstNum;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            reciprocClick=0;
            otherClick=0;
        }
        }else{
            
        secondNum=(Double.parseDouble(String.valueOf(display.getText())));
        
        if(plusClick>0){
            total=firstNum + secondNum ;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            plusClick=0;
        }
        
        if(minusClick>0){
            total=firstNum - secondNum ;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            minusClick=0;
        }
        
        if(multiplyClick>0){
            total=firstNum*secondNum;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            multiplyClick=0;
        }
        
        if(divideClick>0){
            total=firstNum / secondNum ;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            divideClick=0;
        }
        
        if(powClick>0){
            total=Math.pow(firstNum, secondNum) ;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            powClick=0;
        }
        
        if(powMoreClick>0){
            total=Math.pow(firstNum, 1/secondNum) ;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            powMoreClick=0;
        }
        
        if (modulusClick>0){
            total=firstNum%secondNum;
            display.setText(String.valueOf(total));
            firstNum=0;
            secondNum=0;
            modulusClick=0;
        }
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        firstNum =(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        minusClick=1;
        decimalClick=0; 
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        multiplyClick=1;
        decimalClick=0;
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        divideClick=1;
        decimalClick=0;
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("sqr("+firstNum+")");
        otherClick=1;
        squareClick=1;
        decimalClick=0;
        
        
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubeActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("cube("+firstNum+")");
        otherClick=1;
        cubeClick=1;
        decimalClick=0;
    }//GEN-LAST:event_btnCubeActionPerformed

    private void btnReciprocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciprocActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("reciproc("+firstNum+")");
        otherClick=1;
        reciprocClick=1;
        decimalClick=0;
    }//GEN-LAST:event_btnReciprocActionPerformed

    private void powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        powClick=1;
        decimalClick=0;
    }//GEN-LAST:event_powActionPerformed

    private void btnCubeRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubeRootActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        double cbrt=Math.sqrt(firstNum);
        display.setText(String.valueOf(cbrt));
    }//GEN-LAST:event_btnCubeRootActionPerformed

    private void btnRootMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootMoreActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        powMoreClick=1;
        decimalClick=0;
    }//GEN-LAST:event_btnRootMoreActionPerformed

    private void integerValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integerValueActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        int intValue=(int)firstNum;
        display.setText(String.valueOf(intValue));
    }//GEN-LAST:event_integerValueActionPerformed

    private void btnModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulusActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        display.setText("");
        modulusClick=1;
        decimalClick=0;
        
    }//GEN-LAST:event_btnModulusActionPerformed

    private void btnPowerTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerTenActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        double power = Math.pow(10,firstNum);
        display.setText("powten("+String.valueOf(display.getText())+") = "+String.valueOf(power));
        firstNum=0;
        decimalClick=0;
        
    }//GEN-LAST:event_btnPowerTenActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        double answer = Math.sin(Math.toRadians(firstNum));
        display.setText("sin("+String.valueOf(display.getText())+") = "+String.valueOf(answer));
        firstNum=0;
        decimalClick=0;
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        double answer = Math.cos(Math.toRadians(firstNum));
        display.setText("cos("+String.valueOf(display.getText())+") = "+String.valueOf(answer));
        firstNum=0;
        decimalClick=0;
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        double x = firstNum%90;
        double y = (firstNum/90)%2;
        if (x==0 && y!=0){
        display.setText("Invalid input");
    }else{
        double answer = Math.tan(Math.toRadians(firstNum));
        display.setText("tan("+String.valueOf(display.getText())+") = "+String.valueOf(answer));
        firstNum=0;
        decimalClick=0;
        }
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhActionPerformed
        // TODO add your handling code here:
        firstNum=(Double.parseDouble(String.valueOf(display.getText())));
        double answer = Math.sin(Math.toRadians(firstNum));
        display.setText("sinh("+String.valueOf(display.getText())+") = "+String.valueOf(answer));
        firstNum=0;
        decimalClick=0;    
       
    }//GEN-LAST:event_btnSinhActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCube;
    private javax.swing.JButton btnCubeRoot;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnModulus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPowerTen;
    private javax.swing.JButton btnReciproc;
    private javax.swing.JButton btnRoot;
    private javax.swing.JButton btnRootMore;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSinh;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnTan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField display;
    private javax.swing.JButton integerValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private mycalculator.MyCalculator myCalculator1;
    private javax.swing.JButton pow;
    // End of variables declaration//GEN-END:variables
}
